name: Renovate
on:  workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@b6a3618bbc9a5d1faf05b4178eb3f4c351e07b41 # v39.1.2
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
            
